name: Deploy Backend

on:
  push:
    branches:
      - master

concurrency:
  group: backend-production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Copy code to backend directory
        run: |
          rsync -av --delete \
            --filter=':- .gitignore' \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".env" \
            ./ /home/ubuntu/Content-OS-backend/

      - name: Rebuild and restart Docker
        run: |
          cd /home/ubuntu/Content-OS-backend

          docker compose up -d --build

          docker image prune -f

          docker compose ps

      - name: Health check
        run: |
          curl -f http://localhost:8000/check