name: Deploy Backend

on:
  push:
    branches:
      - master

concurrency:
  group: backend-production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Deploy latest backend
        run: |
          set -e

          cd /home/ubuntu/Content-OS-backend

          git fetch origin
          git reset --hard origin/master

          docker compose up -d --build

          docker image prune -f

          docker compose ps

          curl -f http://localhost:8000/check